DROP SCHEMA IF EXISTS sql_private_extensions CASCADE;
DROP SCHEMA IF EXISTS cardano_sql CASCADE;
DROP SCHEMA IF EXISTS cardano_db_sync CASCADE;
DROP SCHEMA IF EXISTS cardano_graphql CASCADE;
DROP SCHEMA IF EXISTS ogmios CASCADE;
