#!/bin/bash

echo "DOCKER_HOST=$DOCKER_HOST"
echo "PODMAN_COMPOSE_PROVIDER=$PODMAN_COMPOSE_PROVIDER"
echo "USER_NAME=$USER_NAME"
echo "ENV_FILE_PATH=$ENV_FILE_PATH"
echo "PROJECT_FILE_PATH=$PROJECT_FILE_PATH"
echo "PODMAN_FILE_PATH=$PODMAN_FILE_PATH"
echo "COMPOSE_ARGS=$1"

# Start the containers using podman-docker with docker-compose
sudo  \
	--preserve-env=DOCKER_HOST,PODMAN_COMPOSE_PROVIDER,USER_NAME,ENV_FILE_PATH,PROJECT_FILE_PATH   \
	-u $USER_NAME  \
	$PODMAN_FILE_PATH compose -f $PROJECT_FILE_PATH --env-file $ENV_FILE_PATH $1

