#!/bin/sh


cronFile="/etc/cron.d/init_cron"
cat "# Cron file generated by 'scripts/cron/entrypoint.sh' \n\n" >> "$cronFile"

# Comment out the job files you want to disable
# Then rebuild cron container with: 
# $ docker compose build cron && docker compose up cron

# Job Files:
# cat /etc/cron.d/koios-lite/init_koios_lite_cron  >> "$cronFile"
cat /etc/cron.d/koios-artifacts/init_koios_artifacts_cron  >> "$cronFile"
cat /etc/cron.d/dbless-cardano-token-registry/init_dbless_cardano_token_registry_cron  >> "$cronFile"

# Load the compiled crontab file
crontab "$cronFile"

echo "Generated Cron file '$cronFile' :"
#cat "$cronFile"
crontab -l

# Start the cron daemon
exec crond -f -d 8
