#!/bin/sh


cronFile="/etc/cron.d/init_cron"
echo "# Cron file generated by 'scripts/cron/entrypoint.sh'" > "$cronFile"

# Comment out the job files you want to disable
# Then rebuild cron container with: 
# $ docker compose build cron && docker compose up cron

# Job Files:
# cat /etc/cron.d/koios-lite/init_cron  >> "$cronFile" && echo >>"$cronFile"
#cat /etc/cron.d/koios-artifacts-1.2.0a/init_cron  >> "$cronFile" && echo >>"$cronFile"
cat /etc/cron.d/koios-artifacts-1.2.0/init_cron  >> "$cronFile" && echo >>"$cronFile"
# cat /etc/cron.d/dbless-cardano-token-registry/init_cron  >> "$cronFile" && echo >>"$cronFile"
cat /etc/cron.d/duckdns/init_cron  >> "$cronFile" && echo >>"$cronFile"

# Load the compiled crontab file
crontab "$cronFile"

echo "Generated Cron file '$cronFile' :"
#cat "$cronFile"
crontab -l

# Start the cron daemon
exec crond -f -d 8
